version: "3.9"

services:
  # frontend:
  #   build: frontend
  #   ports:
  #     - 8501:8501
  #   depends_on:
  #     - backend
  #   volumes:
  #       - ${PATH_TO_LOCAL_STORAGE}:/storage
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ${PATH_TO_LOCAL_STORAGE}:/storage